package retriever.retrievers;


public enum SupplementalColumns {
    ACCOUNT_FIELD1, ACCOUNT_FIELD2, ACCOUNT_FIELD3, ACCOUNT_FIELD4, ACCOUNT_FIELD5, ACCOUNT_FIELD6, ACCOUNT_FIELD7, ACCOUNT_FIELD8, ACCOUNT_FIELD9, ACCOUNT_FIELD10, ACCOUNT_FIELD11, ACCOUNT_FIELD12, ACCOUNT_FIELD13, ACCOUNT_FIELD14, ACCOUNT_FIELD15;
}


